# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# explosionScript.py
# Created on: 2018-04-25 13:45:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: explosionScript <Input_Features> <Distance__value_or_field_> <Layer> <Intersect__3_> <Output_Feature_Class> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Features = arcpy.GetParameterAsText(0)

Distance__value_or_field_ = arcpy.GetParameterAsText(1)

Layer = arcpy.GetParameterAsText(2)

Intersect__3_ = arcpy.GetParameterAsText(3)
if Intersect__3_ == '#' or not Intersect__3_:
    Intersect__3_ = "C:\\Users\\University\\Dropbox\\University\\Advanced_programming\\practicals\\advPrg.gdb\\Intersect" # provide a default value if unspecified

Output_Feature_Class = arcpy.GetParameterAsText(4)

# Local variables:

# Process: Buffer
arcpy.Buffer_analysis(Input_Features, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis([Layer,Output_Feature_Class], Intersect__3_, "ALL", "", "INPUT")

